on:
  pull_request:
    branches:
      - develop
name: Pull request - Integration
jobs:
  integration:
    uses: "pacifico-seguros-org/gradle-pull-request/.github/workflows/main.yml@latest"
    with:
      java_version: "11"
      gradle_version: "6.9.4"
      environment_stage: "develop"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_SP_INT }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_SP_INT }}
      GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
      POLARIS_SERVER_URL: ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
